[package]
name = "egg-java"
version = "0.1.0"
authors = ["lyxell <alyxell@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.6.0"
